# Generated by Django 3.1.7 on 2021-02-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
