# Generated by Django 3.1.7 on 2021-06-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='working',
            field=models.BooleanField(default=False),
        ),
    ]
