# Generated by Django 3.1.7 on 2021-02-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_task_board_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ip_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
