# Generated by Django 2.2.10 on 2021-06-12 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
